url: https://pinedamg.github.io
baseurl: ""

# Site settings
title: MPineda | Full-Stack Developer
email: pinedamg@gmail.com
description: "Delivering reliable and scalable web solutions for e-commerce and beyond. Specializing in PHP, Ruby, and Flutter."

# Team names, titles, and social links (Updated for individual branding)
people:
  - name: Mauricio Gastón Pineda
    pic: profile
    position: Full-Stack Developer
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/pinedamg
      - title: github
        url: https://github.com/pinedamg
      - title: medium
        url: https://pinedamg.medium.com

# Social networks usernames
social:
  - title: linkedin
    url: https://www.linkedin.com/in/pinedamg
  - title: github
    url: https://github.com/pinedamg
  - title: medium
    url: https://pinedamg.medium.com

# Postal address (Placeholder or optional)
address:
  - line: Tigre, Buenos Aires, Argentina

# Build settings
markdown: kramdown
permalink: pretty
