version: "3.8"
services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll-server
    ports:
      - "4000:4000" # Expone el servidor en localhost
    volumes:
      - .:/srv/jekyll # Monta tu proyecto local en el contenedor
    command: jekyll serve --watch --force_polling
